//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEVICE
    {
        public int IdDevice { get; set; }
        public string SerialNumber { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public int IdDeviceType { get; set; }
    
        public virtual DEVICE_TYPE DEVICE_TYPE { get; set; }
        public virtual GATEWAY GATEWAY { get; set; }
        public virtual LIGHT_METER LIGHT_METER { get; set; }
        public virtual WATER_METER WATER_METER { get; set; }
    }
}
