//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEVICE_TYPE
    {
        public DEVICE_TYPE()
        {
            this.DEVICE = new HashSet<DEVICE>();
        }
    
        public int IdDeviceType { get; set; }
        public string DeviceType { get; set; }
    
        public virtual ICollection<DEVICE> DEVICE { get; set; }
    }
}
