//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceManagement.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DeviceManagementEntities : DbContext
    {
        public DeviceManagementEntities()
            : base("name=DeviceManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DEVICE> DEVICE { get; set; }
        public DbSet<DEVICE_TYPE> DEVICE_TYPE { get; set; }
        public DbSet<GATEWAY> GATEWAY { get; set; }
        public DbSet<LIGHT_METER> LIGHT_METER { get; set; }
        public DbSet<WATER_METER> WATER_METER { get; set; }
    }
}
