//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GATEWAY
    {
        public int IdDevice { get; set; }
        public string Ip { get; set; }
        public string Port { get; set; }
    
        public virtual DEVICE DEVICE { get; set; }
    }
}
