CREATE TABLE [dbo].[WATER_METER] (
    [IdDevice] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([IdDevice] ASC),
    CONSTRAINT [FK_WATERMETER_DEVICE] FOREIGN KEY ([IdDevice]) REFERENCES [dbo].[DEVICE] ([IdDevice])
);

